artifacts_root: artifacts  # Root directory for all artifacts

#Data ingestion configuration
data_ingestion:
  root_dir: artifacts/data_ingestion 
  source_URL: https://github.com/LochanaLithira/ML_datasets/raw/refs/heads/main/wine_quality_dataset.zip
  local_data_file: artifacts/data_ingestion/dataset.zip
  unzip_dir: artifacts/data_ingestion

#Data validation configuration
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  status_file: artifacts/data_validation/status.txt

#Data transformation configuration
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/WineQT.csv 

#Model training configuration
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib