name: workflow

#This workflow is triggered on pushes to the main branch, ignoring changes to README.md
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

#Set default permissions for the workflow
permissions:
  contents: read
  id-token: write

#Define the jobs to be run in the workflow
jobs:
  #Continuous Integration Job
  integration:
    name: Continuous Integration  #Job name
    runs-on: ubuntu-latest  #Use the latest Ubuntu runner
    steps:  #Define the steps for the job
      - name: Checkout Code  #Step to checkout the repository code
        uses: actions/checkout@v3  #Use the checkout action

      - name: Lint code  #Step to lint the code
        run: echo "Linting repository"  #Placeholder command for linting

      - name: Run unit tests  #Step to run unit tests
        run: echo "Running unit tests"  #Placeholder command for unit tests

  #Continuous Delivery Job
  build-and-push-ecr-image:
    name: Continuous Delivery  #Job name
    needs: integration  #This job depends on the completion of the integration job
    runs-on: ubuntu-latest  #Use the latest Ubuntu runner
    steps:
      - name: Checkout Code  #Step to checkout the repository code
        uses: actions/checkout@v3  #Use the checkout action

      - name: Install Utilities #Step to install necessary utilities
        run: |  #Run multiple commands
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials  #Step to configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  #Use the AWS configure credentials action
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  #Access key from secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  #Secret key
          aws-region: ${{ secrets.AWS_REGION }}  #AWS region

      - name: Login to Amazon ECR  #Step to log in to Amazon ECR
        id: login-ecr  #ID for the step
        uses: aws-actions/amazon-ecr-login@v1  #Use the Amazon ECR login action

      - name: Build, tag, and push image to Amazon ECR  #Step to build, tag, and push Docker image
        id: build-image  #ID for the step
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  #ECR registry from previous step
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}  #ECR repository name
          IMAGE_TAG: latest  #Image tag
        run: |  #Run multiple commands
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .  #Build Docker image
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  #Push Docker image to ECR
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"  #Set output variable for image URI

  #Continuous Deployment Job
  Continuous Deployment:
    name: Continuous Deployment  #Job name
    needs: build-and-push-ecr-image  #This job depends on the completion of the build-and-push-ecr-image job
    runs-on: self-hosted  #Use the self-hosted runner
    steps:
      - name: Checkout Code  #Step to checkout the repository code
        uses: actions/checkout@v3  #Use the checkout action

      - name: Configure AWS credentials  #Step to configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  #Use the AWS configure credentials action
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  #Access key from secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  #Secret key
          aws-region: ${{ secrets.AWS_REGION }}  #AWS region

      - name: Login to Amazon ECR  #Step to log in to Amazon ECR
        id: login-ecr  #ID for the step
        uses: aws-actions/amazon-ecr-login@v1  #Use the Amazon ECR login action

      - name: Pull latest image  #Step to pull the latest Docker image
        run: |  #Run multiple commands
          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{secrets.ECR_REPOSITORY_NAME}}:latest  #Pull the Docker image from ECR

      - name: Stop and remove container if running  #Step to stop and remove existing Docker container
        run: |  #Run multiple commands
          docker ps -q --filter "name=cnncls" | grep -q . && docker stop cnncls && docker rm -fv cnncls

      - name: Run Docker Image to serve users  #Step to run the Docker image
        run: |  #Run multiple commands
          docker run -d -p 5000:5000 --name=cnncls -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}'  ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:latest  #Run the Docker container

      - name: Clean previous images and containers  #Step to clean up previous Docker images and containers
        run: |  #Run multiple commands
          docker system prune -f  #Remove all stopped containers
  

    